# https://docs.docker.com/compose/compose-file
version: "3.6"
 
# https://docs.docker.com/compose/compose-file/#service-configuration-reference
services:
    web-yht:
        image: udovicic/echo:apache-php7.2
        external_links:
        - "mysql5.6:db"
        - "redis"
        ports:
        - "8082:80"
        volumes:
        - ./apache/auth.json:/root/.composer/auth.json
        - ./apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
        - ./php/xdebug.ini:/etc/php/7.2/mods-available/xdebug.ini
        - ../:/var/www/html
        environment:
        - TERM=xterm-256color
        - APACHE_RUN_USER=1000
        network_mode : bridge